# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Proxy Update Job

on:
  repository_dispatch:
    types: [update_proxy]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - run: npm i
    - run: npm install -g protractor
    - run: webdriver-manager update --versions.chrome=$(google-chrome --version | cut -d ' ' -f 3)
    - run: protractor conf.js
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git commit -m "Updated Proxies" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
